export const targetDisplayNameMap = {
    'wk inc covid hosp': 'Weekly Incident COVID-19 Hospitalizations',
    'wk inc covid prop ed visits': "Proportion of ED Visits due to COVID-19",
    'wk inc flu hosp': 'Weekly Incident Flu Hospitalizations',
    'wk inc rsv hosp': 'Weekly Incident RSV Hospitalizations',
    'wk inc rsv prop ed visits':  'Proportion of ED Visits due to RSV'
};

export const nhsnTargetsToColumnsMap = {
    'Raw Patient Counts': [
        'Total Adult COVID-19 Admissions',
        'Total Adult Influenza Admissions',
        'Total Adult RSV Admissions',
        'Total COVID-19 Admissions',
        'Total ICU Patients Hospitalized with COVID-19 ',
        'Total ICU Patients Hospitalized with Influenza',
        'Total ICU Patients Hospitalized with RSV',
        'Total Influenza Admissions',
        'Total Patients Hospitalized with COVID-19',
        'Total Patients Hospitalized with Influenza',
        'Total Patients Hospitalized with RSV',
        'Total Pediatric COVID-19 Admissions',
        'Total Pediatric Influenza Admissions',
        'Total Pediatric RSV Admissions',
        'Total RSV Admissions',
        'Number of Adult COVID-19 Admissions, 18-49 years',
        'Number of Adult COVID-19 Admissions, 50-64 years',
        'Number of Adult COVID-19 Admissions, 65-74 years',
        'Number of Adult COVID-19 Admissions, 75+ years',
        'Number of Adult ICU Patients Hospitalized with COVID-19',
        'Number of Adult ICU Patients Hospitalized with Influenza',
        'Number of Adult ICU Patients Hospitalized with RSV',
        'Number of Adult Influenza Admissions, 18-49 years',
        'Number of Adult Influenza Admissions, 50-64 years',
        'Number of Adult Influenza Admissions, 65-74 years',
        'Number of Adult Influenza Admissions, 75+ years',
        'Number of Adult Patients Hospitalized with COVID-19',
        'Number of Adult Patients Hospitalized with Influenza',
        'Number of Adult Patients Hospitalized with RSV',
        'Number of Adult RSV Admissions, 18-49 years',
        'Number of Adult RSV Admissions, 50-64 years',
        'Number of Adult RSV Admissions, 65-74 years',
        'Number of Adult RSV Admissions, 75+ years',
        'Number of COVID-19 Admissions, unknown age',
        'Number of Influenza Admissions, unknown age',
        'Number of Pedatric Patients Hospitalized with Influenza',
        'Number of Pediatric COVID-19 Admissions, 0-4 years',
        'Number of Pediatric COVID-19 Admissions, 5-17 years',
        'Number of Pediatric ICU Patients Hospitalized with COVID-19',
        'Number of Pediatric ICU Patients Hospitalized with Influenza',
        'Number of Pediatric ICU Patients Hospitalized with RSV',
        'Number of Pediatric Influenza Admissions, 0-4 years',
        'Number of Pediatric Influenza Admissions, 5-17 years',
        'Number of Pediatric Patients Hospitalized with COVID-19',
        'Number of Pediatric Patients Hospitalized with RSV',
        'Number of Pediatric RSV Admissions, 0-4 years',
        'Number of Pediatric RSV Admissions, 5-17 years',
        'Number of RSV Admissions, unknown age',
    ],
    'Hospital Admission Rates': [
        'Total Number of Adult COVID-19 Admissions per 100,000 population',
        'Total Number of Adult Influenza Admissions per 100,000 population',
        'Total Number of Adult RSV Admissions per 100,000 population',
        'Total Number of Pediatric COVID-19 Admissions per 100,000 population',
        'Total Number of Pediatric Influenza Admissions per 100,000 population',
        'Total Number of Pediatric RSV Admissions per 100,000 population',
        'Total number of COVID-19 Admissions per 100,000 population',
        'Total number of Influenza Admissions per 100,000 population',
        'Total number of RSV Admissions per 100,000 population',
        'Number of Adult COVID-19 Admissions, 18-49 years, per 100,000 population',
        'Number of Adult COVID-19 Admissions, 50-64 years, per 100,000 population',
        'Number of Adult COVID-19 Admissions, 65-74 years, per 100,000 population',
        'Number of Adult COVID-19 Admissions, 75+ years, per 100,000 population',
        'Number of Adult Influenza Admissions, 18-49 years, per 100,000 population',
        'Number of Adult Influenza Admissions, 50-64 years, per 100,000 population',
        'Number of Adult Influenza Admissions, 65-74 years, per 100,000 population',
        'Number of Adult Influenza Admissions, 75+ years, per 100,000 population',
        'Number of Adult RSV Admissions, 18-49 years, per 100,000 population',
        'Number of Adult RSV Admissions, 50-64 years, per 100,000 population',
        'Number of Adult RSV Admissions, 65-74 years, per 100,000 population',
        'Number of Adult RSV Admissions, 75+ years, per 100,000 population',
        'Number of Pediatric COVID-19 Admissions, 0-4 years, per 100,000 population',
        'Number of Pediatric COVID-19 Admissions, 5-17 years, per 100,000 population',
        'Number of Pediatric Influenza Admissions, 0-4 years, per 100,000 population',
        'Number of Pediatric Influenza Admissions, 5-17 years, per 100,000 population',
        'Number of Pediatric RSV Admissions, 0-4 years, per 100,000 population',
        'Number of Pediatric RSV Admissions, 5-17 years, per 100,000 population',
    ],
    'Hospital Admission Percents': [
        'Percent Adult COVID-19 Admissions',
        'Percent Adult Influenza Admissions',
        'Percent Adult RSV Admissions',
        'Percent Pediatric COVID-19 Admissions',
        'Percent Pediatric Influenza Admissions',
        'Percent Pediatric RSV Admissions',
    ],
    'Raw Bed Capacity': [
        'Number of Adult ICU Beds',
        'Number of Adult ICU Beds Occupied',
        'Number of Adult Inpatient Beds',
        'Number of Adult Inpatient Beds Occupied',
        'Number of ICU Beds',
        'Number of ICU Beds Occupied',
        'Number of Inpatient Beds',
        'Number of Inpatient Beds Occupied',
        'Number of Pediatric ICU Beds',
        'Number of Pediatric ICU Beds Occupied',
        'Number of Pediatric Inpatient Beds Occupied',
        'Number of Pediatric Inpatient beds'
    ],
    'Bed Capacity Percents': [
        'Percent ICU Beds Occupied',
        'Percent ICU Beds Occupied by COVID-19 Patients',
        'Percent ICU Beds Occupied by Influenza Patients',
        'Percent ICU Beds Occupied by RSV Patients',
        'Percent Inpatient Beds Occupied',
        'Percent Inpatient Beds Occupied by COVID-19 Patients',
        'Percent Inpatient Beds Occupied by Influenza Patients',
        'Percent Inpatient Beds Occupied by RSV Patients',
    ],
    'Absolute Percent Change': [
        'Absolute Change in the Percent Hospitals Reporting  Influenza Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Adult COVID-19 Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Adult Influenza Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Adult RSV Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting COVID-19 Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with COVID-19 from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with Influenza from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with RSV from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Number of ICU Beds Occupied from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Number of ICU Beds from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Number of Inpatient Beds Occupied from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Number of Inpatient Beds from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Pediatric COVID-19 Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Pediatric Influenza Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Pediatric RSV Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting RSV Admissions from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with COVID-19 from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with RSV from Prior Week',
        'Absolute Change in the Percent Hospitals Reporting TotalPatients Hospitalized with Influenza from Prior Week',
    ]
}